---
title: "Meteorologia da Poluição do ar"
output: 
  html_notebook:
    theme: lumen
    toc: yes
    toc_float: yes
    highlight: tango
---

Notas de aula do curso "Meteorologia da Poluição do Ar", ministrado no IAG no segundo semestre de 2018 pela professora Maria de Fátima.

## Aula 1 - 08/08/2018

<hr>

Aerossól:

- Distribuição de Aerossóis: 10km resolution W. Putmanm, NASA Goddard

Smog:

- Smog = **sm**oke + f**og**

- Ozônio, hidrocarbonetos, nitrogênio, partículas e outros compostos reativos. 

Monitoramento de poluição do ar:

- A Rússia não monitora ou não disponibiliza dados de poluição.

- A legislação chilena é bem rigorosa com o monitoramento ambiental.

- Existem muito poucas medições na África.

- Ásia (Índia e China) apresentam as médias mais elevadas de poluição.

Fontes de dados:

- [Air Pollution in World](aqicn.org/map/world)

- [Site da Organização Mundial da Saúde](maps.who.int/airpollution)

- Instituto de energia e meio ambiente: [Plataforma da Qualidade do Ar](qualidadedoar.org.br)


## Aula 2 - 10/08/2018

<hr>

- Observando o espectro de energia que chega na Terra, é possível calcular a temperatura do corpo emissor.

- Calor sensível vs calor latente.

- Transferência de energia: convecção

- Camada limite planetária (CLP): altura máxima em que a superfície influencia a atmosfera.

- Turbulência 
   - térmica
   - mecânica (fricção e rugosidade do terreno)
   
## Aula 3 - 15/08/2018

<hr>

#### Introdução

SLCP (short-lived climate pollutants):

- O$_3$
- Partículas (PM)
- Black carbon

<hr>

#### Formação do ozônio

Abaixo as reações químicas envolvidas na formação do ozônio:

- NO + radicais (HO$_2\cdot$, OH$\cdot$) $\rightarrow$ NO$_2$ + OH (H)

- NO$_2$ $\stackrel{h\nu}{\rightarrow}$ NO + O

- O$_2$ + O $\rightarrow$ O$_3$ 

- NO + O$_3$  $\rightarrow$ NO$_2$ (reação de consumo)


O NO$_2$ vem da queima de combustíveis:

- HC + O$_2$ $\rightarrow$ CO$_2$ + H$_2$O + energia

Como os hidrocarbonetos (HC) quase sempre não são puros, essa reação também pode gerar CO, SO$_2$, NO e NO$_2$

Os radicais (HO$_2\cdot$, OH$\cdot$) vem primariamente dos COV: HC + oxigenados + HC não queimados + álcoois

<hr>

#### Pesquisar

- Química: o que são radicais?

- O que significa h$\nu$?

- O que é deposição?

## Aula 4 - 17/08/2018

Na reação A + B $\rightarrow$ C + D, a variação de C é dada por

$$
\frac{dC}{dt} = k A B
$$

<hr>

Plataforma para avaliar inventário de emissões no Brasil: 
[plataforma.seeg.eco.br/total_emission](plataforma.seeg.eco.br/total_emission)

Plataforma para avaliar inventário de emissões global:
[www.iiasa.ac.at](www.iiasa.ac.at)
